# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lx/Multiple_ParaRC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lx/Multiple_ParaRC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lx/Multiple_ParaRC/CMakeFiles /home/lx/Multiple_ParaRC//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lx/Multiple_ParaRC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Sim_centralize

# Build rule for target.
Sim_centralize: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Sim_centralize
.PHONY : Sim_centralize

# fast build rule for target.
Sim_centralize/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Sim_centralize.dir/build.make src/CMakeFiles/Sim_centralize.dir/build
.PHONY : Sim_centralize/fast

#=============================================================================
# Target rules for targets named Sim_offline

# Build rule for target.
Sim_offline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Sim_offline
.PHONY : Sim_offline

# fast build rule for target.
Sim_offline/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Sim_offline.dir/build.make src/CMakeFiles/Sim_offline.dir/build
.PHONY : Sim_offline/fast

#=============================================================================
# Target rules for targets named Sim_parallel

# Build rule for target.
Sim_parallel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Sim_parallel
.PHONY : Sim_parallel

# fast build rule for target.
Sim_parallel/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Sim_parallel.dir/build.make src/CMakeFiles/Sim_parallel.dir/build
.PHONY : Sim_parallel/fast

#=============================================================================
# Target rules for targets named Sim_multiple

# Build rule for target.
Sim_multiple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Sim_multiple
.PHONY : Sim_multiple

# fast build rule for target.
Sim_multiple/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Sim_multiple.dir/build.make src/CMakeFiles/Sim_multiple.dir/build
.PHONY : Sim_multiple/fast

#=============================================================================
# Target rules for targets named MulSim_centralize

# Build rule for target.
MulSim_centralize: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MulSim_centralize
.PHONY : MulSim_centralize

# fast build rule for target.
MulSim_centralize/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/MulSim_centralize.dir/build.make src/CMakeFiles/MulSim_centralize.dir/build
.PHONY : MulSim_centralize/fast

#=============================================================================
# Target rules for targets named MulSim_offline

# Build rule for target.
MulSim_offline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MulSim_offline
.PHONY : MulSim_offline

# fast build rule for target.
MulSim_offline/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/MulSim_offline.dir/build.make src/CMakeFiles/MulSim_offline.dir/build
.PHONY : MulSim_offline/fast

#=============================================================================
# Target rules for targets named MulSim_parallel

# Build rule for target.
MulSim_parallel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MulSim_parallel
.PHONY : MulSim_parallel

# fast build rule for target.
MulSim_parallel/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/MulSim_parallel.dir/build.make src/CMakeFiles/MulSim_parallel.dir/build
.PHONY : MulSim_parallel/fast

#=============================================================================
# Target rules for targets named ParaCoordinator

# Build rule for target.
ParaCoordinator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ParaCoordinator
.PHONY : ParaCoordinator

# fast build rule for target.
ParaCoordinator/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ParaCoordinator.dir/build.make src/CMakeFiles/ParaCoordinator.dir/build
.PHONY : ParaCoordinator/fast

#=============================================================================
# Target rules for targets named ParaAgent

# Build rule for target.
ParaAgent: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ParaAgent
.PHONY : ParaAgent

# fast build rule for target.
ParaAgent/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ParaAgent.dir/build.make src/CMakeFiles/ParaAgent.dir/build
.PHONY : ParaAgent/fast

#=============================================================================
# Target rules for targets named CodeTest

# Build rule for target.
CodeTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CodeTest
.PHONY : CodeTest

# fast build rule for target.
CodeTest/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/CodeTest.dir/build.make src/CMakeFiles/CodeTest.dir/build
.PHONY : CodeTest/fast

#=============================================================================
# Target rules for targets named GenData

# Build rule for target.
GenData: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GenData
.PHONY : GenData

# fast build rule for target.
GenData/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/GenData.dir/build.make src/CMakeFiles/GenData.dir/build
.PHONY : GenData/fast

#=============================================================================
# Target rules for targets named MultipleCoor

# Build rule for target.
MultipleCoor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MultipleCoor
.PHONY : MultipleCoor

# fast build rule for target.
MultipleCoor/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/MultipleCoor.dir/build.make src/CMakeFiles/MultipleCoor.dir/build
.PHONY : MultipleCoor/fast

#=============================================================================
# Target rules for targets named Multiple_Coloring

# Build rule for target.
Multiple_Coloring: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Multiple_Coloring
.PHONY : Multiple_Coloring

# fast build rule for target.
Multiple_Coloring/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Multiple_Coloring.dir/build.make src/CMakeFiles/Multiple_Coloring.dir/build
.PHONY : Multiple_Coloring/fast

#=============================================================================
# Target rules for targets named Multiple_Failure

# Build rule for target.
Multiple_Failure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Multiple_Failure
.PHONY : Multiple_Failure

# fast build rule for target.
Multiple_Failure/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Multiple_Failure.dir/build.make src/CMakeFiles/Multiple_Failure.dir/build
.PHONY : Multiple_Failure/fast

#=============================================================================
# Target rules for targets named Brute_Force

# Build rule for target.
Brute_Force: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Brute_Force
.PHONY : Brute_Force

# fast build rule for target.
Brute_Force/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Brute_Force.dir/build.make src/CMakeFiles/Brute_Force.dir/build
.PHONY : Brute_Force/fast

#=============================================================================
# Target rules for targets named NewBruteForce

# Build rule for target.
NewBruteForce: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NewBruteForce
.PHONY : NewBruteForce

# fast build rule for target.
NewBruteForce/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/NewBruteForce.dir/build.make src/CMakeFiles/NewBruteForce.dir/build
.PHONY : NewBruteForce/fast

#=============================================================================
# Target rules for targets named genMLP

# Build rule for target.
genMLP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 genMLP
.PHONY : genMLP

# fast build rule for target.
genMLP/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/genMLP.dir/build.make src/CMakeFiles/genMLP.dir/build
.PHONY : genMLP/fast

#=============================================================================
# Target rules for targets named NewgenMLP

# Build rule for target.
NewgenMLP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NewgenMLP
.PHONY : NewgenMLP

# fast build rule for target.
NewgenMLP/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/NewgenMLP.dir/build.make src/CMakeFiles/NewgenMLP.dir/build
.PHONY : NewgenMLP/fast

#=============================================================================
# Target rules for targets named RepairSimulator

# Build rule for target.
RepairSimulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RepairSimulator
.PHONY : RepairSimulator

# fast build rule for target.
RepairSimulator/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/RepairSimulator.dir/build.make src/CMakeFiles/RepairSimulator.dir/build
.PHONY : RepairSimulator/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) $(MAKESILENT) -f src/common/CMakeFiles/common.dir/build.make src/common/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) $(MAKESILENT) -f src/dist/CMakeFiles/dist.dir/build.make src/dist/CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named ec

# Build rule for target.
ec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ec
.PHONY : ec

# fast build rule for target.
ec/fast:
	$(MAKE) $(MAKESILENT) -f src/ec/CMakeFiles/ec.dir/build.make src/ec/CMakeFiles/ec.dir/build
.PHONY : ec/fast

#=============================================================================
# Target rules for targets named sol

# Build rule for target.
sol: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sol
.PHONY : sol

# fast build rule for target.
sol/fast:
	$(MAKE) $(MAKESILENT) -f src/sol/CMakeFiles/sol.dir/build.make src/sol/CMakeFiles/sol.dir/build
.PHONY : sol/fast

#=============================================================================
# Target rules for targets named protocol

# Build rule for target.
protocol: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 protocol
.PHONY : protocol

# fast build rule for target.
protocol/fast:
	$(MAKE) $(MAKESILENT) -f src/protocol/CMakeFiles/protocol.dir/build.make src/protocol/CMakeFiles/protocol.dir/build
.PHONY : protocol/fast

#=============================================================================
# Target rules for targets named util

# Build rule for target.
util: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 util
.PHONY : util

# fast build rule for target.
util/fast:
	$(MAKE) $(MAKESILENT) -f src/util/CMakeFiles/util.dir/build.make src/util/CMakeFiles/util.dir/build
.PHONY : util/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Brute_Force"
	@echo "... CodeTest"
	@echo "... GenData"
	@echo "... MulSim_centralize"
	@echo "... MulSim_offline"
	@echo "... MulSim_parallel"
	@echo "... MultipleCoor"
	@echo "... Multiple_Coloring"
	@echo "... Multiple_Failure"
	@echo "... NewBruteForce"
	@echo "... NewgenMLP"
	@echo "... ParaAgent"
	@echo "... ParaCoordinator"
	@echo "... RepairSimulator"
	@echo "... Sim_centralize"
	@echo "... Sim_multiple"
	@echo "... Sim_offline"
	@echo "... Sim_parallel"
	@echo "... common"
	@echo "... dist"
	@echo "... ec"
	@echo "... genMLP"
	@echo "... protocol"
	@echo "... sol"
	@echo "... util"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

