// GenPredictedTrace.cc
// 把真实 trace 经过 MLPredictor 处理，输出预测 trace 文件
// 同时输出详细对比报告：预测正确/错误分析 + 影响条带分析
//
// 用法:
//   ./GenPredictedTrace <trace_file> <total_nodes> <fpr> <fnr> <output_file> [seed] [placement_file]
//
// 示例:
//   ./GenPredictedTrace trace.txt 40 0.002 0.05 trace_ml_low.txt  42 stripeStore/sim_40_1000_14_10_4
//   ./GenPredictedTrace trace.txt 40 0.025 0.05 trace_ml_high.txt 42 stripeStore/sim_40_1000_14_10_4
//   ./GenPredictedTrace trace.txt 40 0.0   0.0  trace_perfect.txt    # 完美预测（验证用）

#include "inc/include.hh"
#include "common/TraceReader.hh"
#include "MLPredictor.hh"

#include <fstream>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <unordered_set>

using namespace std;

void usage() {
    cout << "Usage: ./GenPredictedTrace" << endl;
    cout << "   1. trace_file      (真实 trace 文件路径)" << endl;
    cout << "   2. total_nodes     (集群总节点数, e.g. 40)" << endl;
    cout << "   3. fpr             (误报率, e.g. 0.002)" << endl;
    cout << "   4. fnr             (漏报率, e.g. 0.05)" << endl;
    cout << "   5. output_file     (输出预测 trace 路径)" << endl;
    cout << "   6. seed            (随机种子, 可选, 默认42)" << endl;
    cout << "   7. placement_file  (条带分布文件, 可选, 用于显示影响条带)" << endl;
}

// 辅助：把节点列表格式化为字符串
string nodeListStr(const vector<int>& nodes) {
    if (nodes.empty()) return "(无)";
    string s = "[";
    for (int i = 0; i < (int)nodes.size(); i++) {
        if (i) s += ",";
        s += to_string(nodes[i]);
    }
    s += "]";
    return s;
}

int main(int argc, char** argv) {
    if (argc < 6) { usage(); return 0; }

    string trace_file    = argv[1];
    int    total_nodes   = atoi(argv[2]);
    double fpr           = atof(argv[3]);
    double fnr           = atof(argv[4]);
    string output_file   = argv[5];
    int    seed          = (argc > 6) ? atoi(argv[6]) : 42;
    string placement_file = (argc > 7) ? argv[7] : "";

    cout << "============================================" << endl;
    cout << "  GenPredictedTrace" << endl;
    cout << "============================================" << endl;
    printf("  Input trace:    %s\n", trace_file.c_str());
    printf("  Total nodes:    %d\n", total_nodes);
    printf("  FPR:            %.4f  (误报率)\n", fpr);
    printf("  FNR:            %.4f  (漏报率)\n", fnr);
    printf("  Output:         %s\n", output_file.c_str());
    printf("  Seed:           %d\n", seed);

    // ── 加载 trace ──────────────────────────────────────────────
    TraceReader reader;
    if (!reader.loadTrace(trace_file)) {
        cerr << "Failed to load trace: " << trace_file << endl;
        return 1;
    }

    // ── 加载 placement（可选）──────────────────────────────────
    // stripe_id -> 节点列表
    vector<vector<int>> stripe_placement;
    if (!placement_file.empty()) {
        ifstream pf(placement_file);
        if (!pf.is_open()) {
            cerr << "Warning: cannot open placement file: " << placement_file << endl;
        } else {
            string line;
            while (getline(pf, line)) {
                if (line.empty()) continue;
                istringstream iss(line);
                vector<int> nodes;
                int nid;
                while (iss >> nid) nodes.push_back(nid);
                stripe_placement.push_back(nodes);
            }
            printf("  Placement:      %s (%zu stripes)\n",
                   placement_file.c_str(), stripe_placement.size());
        }
    }
    cout << endl;

    // ── 初始化预测器 ─────────────────────────────────────────────
    MLPredictor predictor(total_nodes, fpr, fnr, seed);

    // ── 打开输出文件 ─────────────────────────────────────────────
    ofstream outfile(output_file);
    if (!outfile.is_open()) {
        cerr << "Failed to open output file: " << output_file << endl;
        return 1;
    }
    outfile << "# Predicted trace generated by GenPredictedTrace" << endl;
    outfile << "# Source: " << trace_file << endl;
    outfile << "# FPR=" << fpr << " FNR=" << fnr << " seed=" << seed << endl;
    outfile << "# Format: timestamp num_failures node_id1 node_id2 ..." << endl;
    outfile << "#" << endl;

    // ── 累计统计 ─────────────────────────────────────────────────
    int total_real_fails = 0, total_pred_fails = 0;
    int total_tp = 0, total_fp = 0, total_fn = 0;
    int days_with_fp = 0, days_with_fn = 0;

    // ── 逐事件处理 ───────────────────────────────────────────────
    while (reader.hasCurrentEvent()) {
        TraceEvent* event = reader.getCurrentEvent();
        int ts = event->timestamp;

        // ML 预测
        vector<int> predicted = predictor.predictNextFailures(event);

        // 分类节点
        unordered_set<int> real_set(event->fail_node_ids.begin(), event->fail_node_ids.end());
        unordered_set<int> pred_set(predicted.begin(), predicted.end());

        vector<int> tp_nodes, fp_nodes, fn_nodes;
        for (int nid : predicted) {
            if (real_set.count(nid)) tp_nodes.push_back(nid);
            else                     fp_nodes.push_back(nid);
        }
        for (int nid : event->fail_node_ids) {
            if (!pred_set.count(nid)) fn_nodes.push_back(nid);
        }

        total_tp         += tp_nodes.size();
        total_fp         += fp_nodes.size();
        total_fn         += fn_nodes.size();
        total_real_fails += event->fail_node_ids.size();
        total_pred_fails += predicted.size();
        if (!fp_nodes.empty()) days_with_fp++;
        if (!fn_nodes.empty()) days_with_fn++;

        // 写入预测 trace
        outfile << ts << " " << predicted.size();
        for (int nid : predicted) outfile << " " << nid;
        outfile << "\n";

        // ── 详细终端输出 ─────────────────────────────────────────
        bool has_any = !event->fail_node_ids.empty() || !predicted.empty();
        bool perfect = fp_nodes.empty() && fn_nodes.empty();

        cout << "┌── Day " << ts;
        if (!has_any)        cout << "  [平静：无故障无预测]";
        else if (perfect)    cout << "  [预测完全正确 ✓]";
        else                 cout << "  [预测有误差 ✗]";
        cout << "\n";

        // 真实 vs 预测节点
        printf("│  真实故障节点: %-30s  (%d 个)\n",
               nodeListStr(event->fail_node_ids).c_str(),
               (int)event->fail_node_ids.size());
        printf("│  ML预测故障:   %-30s  (%d 个)\n",
               nodeListStr(predicted).c_str(),
               (int)predicted.size());

        // 预测准确性细节
        if (!tp_nodes.empty())
            printf("│  ✓ 预测正确(TP): %-25s → 将正确触发修复\n",
                   nodeListStr(tp_nodes).c_str());
        if (!fp_nodes.empty())
            printf("│  ✗ 误报   (FP): %-25s → 节点实际正常，将触发不必要修复\n",
                   nodeListStr(fp_nodes).c_str());
        if (!fn_nodes.empty())
            printf("│  ✗ 漏报   (FN): %-25s → 节点实际已故障，修复被延误！\n",
                   nodeListStr(fn_nodes).c_str());
        if (!has_any)
            cout << "│  (本时间步无故障，预测也无故障，完全正确)\n";

        // ── 条带影响分析 ─────────────────────────────────────────
        if (!stripe_placement.empty() && has_any) {
            vector<int> real_stripes, fp_stripes, fn_stripes, extra_repair_stripes;

            for (int sid = 0; sid < (int)stripe_placement.size(); sid++) {
                const auto& nodes = stripe_placement[sid];
                bool has_real = false, has_fp = false, has_fn = false;
                for (int nid : nodes) {
                    if (real_set.count(nid)) has_real = true;
                    if (pred_set.count(nid) && !real_set.count(nid)) has_fp = true;
                    if (real_set.count(nid) && !pred_set.count(nid)) has_fn = true;
                }
                if (has_real)  real_stripes.push_back(sid);
                if (has_fp)    fp_stripes.push_back(sid);
                if (has_fn)    fn_stripes.push_back(sid);
            }

            if (!real_stripes.empty()) {
                cout << "│  [条带] 真实故障波及 " << real_stripes.size() << " 个条带: ";
                for (int i = 0; i < min((int)real_stripes.size(), 8); i++)
                    cout << "S" << real_stripes[i] << " ";
                if (real_stripes.size() > 8) cout << "...(" << real_stripes.size()-8 << "more)";
                cout << "\n";
            }
            if (!fp_stripes.empty()) {
                cout << "│  [条带] 误报导致多余修复 " << fp_stripes.size() << " 个条带: ";
                for (int i = 0; i < min((int)fp_stripes.size(), 8); i++)
                    cout << "S" << fp_stripes[i] << " ";
                if (fp_stripes.size() > 8) cout << "...(" << fp_stripes.size()-8 << "more)";
                cout << "  ← 浪费修复资源\n";
            }
            if (!fn_stripes.empty()) {
                cout << "│  [条带] 漏报导致修复遗漏 " << fn_stripes.size() << " 个条带: ";
                for (int i = 0; i < min((int)fn_stripes.size(), 8); i++)
                    cout << "S" << fn_stripes[i] << " ";
                if (fn_stripes.size() > 8) cout << "...(" << fn_stripes.size()-8 << "more)";
                cout << "  ← 数据丢失风险\n";
            }
        }

        cout << "└────────────────────────────────────────────\n\n";

        reader.advance();
    }

    outfile.close();

    // ── 汇总报告 ─────────────────────────────────────────────────
    int events = reader.getEventCount();
    cout << "\n╔══════════════════════════════════════════════╗" << endl;
    cout << "║              汇总统计报告                    ║" << endl;
    cout << "╠══════════════════════════════════════════════╣" << endl;
    printf("║  Trace 总时间步:      %-6d                 ║\n", events);
    printf("║  真实故障节点总数:    %-6d                 ║\n", total_real_fails);
    printf("║  预测故障节点总数:    %-6d                 ║\n", total_pred_fails);
    cout << "╠══════════════════════════════════════════════╣" << endl;
    printf("║  True  Positives(TP): %-6d  (正确预测故障) ║\n", total_tp);
    printf("║  False Positives(FP): %-6d  (误报，多余修复)║\n", total_fp);
    printf("║  False Negatives(FN): %-6d  (漏报，延误修复)║\n", total_fn);
    cout << "╠══════════════════════════════════════════════╣" << endl;
    if (total_tp + total_fp > 0)
        printf("║  Precision(精确率):   %.4f               ║\n",
               1.0*total_tp/(total_tp+total_fp));
    if (total_tp + total_fn > 0)
        printf("║  Recall(召回率):      %.4f               ║\n",
               1.0*total_tp/(total_tp+total_fn));
    printf("║  含误报的天数:        %-6d / %-6d        ║\n", days_with_fp, events);
    printf("║  含漏报的天数:        %-6d / %-6d        ║\n", days_with_fn, events);
    cout << "╠══════════════════════════════════════════════╣" << endl;
    cout << "║  FP影响: 触发不必要修复，浪费修复带宽       ║" << endl;
    cout << "║  FN影响: 故障被遗漏，容错窗口缩小，存在     ║" << endl;
    cout << "║          数据丢失风险                        ║" << endl;
    cout << "╠══════════════════════════════════════════════╣" << endl;
    printf("║  输出文件: %-34s║\n", output_file.c_str());
    cout << "╚══════════════════════════════════════════════╝" << endl;

    return 0;
}
