// GenTrace.cc
// 随机生成故障 trace 文件，支持突发故障模式
//
// 故障模型：
//   背景故障：每节点每天以 fail_prob 概率独立故障，repair_days 天后恢复
//   突发故障：每隔若干天，集中在某个节点组（模拟机架/批量老化）故障
//             突发故障的节点来自同一批 placement，能直接威胁条带安全
//
// 用法:
//   ./GenTrace <total_nodes> <num_days> <fail_prob> <output_file>
//              [seed] [repair_days] [burst_interval] [burst_size] [max_fails_per_day]
//
// 参数说明:
//   burst_interval  : 每隔多少天发生一次突发故障（0=不启用，默认30）
//   burst_size      : 每次突发同时故障的节点数（默认 tolerance+1=5）
//
// 示例:
//   ./GenTrace 40 365 0.02 trace.txt 42 7 30 3   # 每30天一次突发，每次3节点
//   ./GenTrace 40 365 0.02 trace.txt 42 7 0       # 纯随机，不启用突发

#include <iostream>
#include <fstream>
#include <vector>
#include <random>
#include <algorithm>
#include <unordered_map>
#include <unordered_set>

using namespace std;

void usage() {
    cout << "Usage: ./GenTrace" << endl;
    cout << "   1. total_nodes      (cluster node count, e.g. 40)" << endl;
    cout << "   2. num_days         (simulation days, e.g. 365)" << endl;
    cout << "   3. fail_prob        (per-node per-day background failure prob, e.g. 0.02)" << endl;
    cout << "   4. output_file      (output trace file path)" << endl;
    cout << "   5. seed             (random seed, optional, default 42)" << endl;
    cout << "   6. repair_days      (days to recover, optional, default 7)" << endl;
    cout << "   7. burst_interval   (days between bursts, 0=disabled, default 30)" << endl;
    cout << "   8. burst_size       (nodes failing per burst, default 3)" << endl;
    cout << "   9. max_fails_per_day(max failures per day, default unlimited)" << endl;
}

int main(int argc, char** argv) {
    if (argc < 5) { usage(); return 0; }

    int    total_nodes       = atoi(argv[1]);
    int    num_days          = atoi(argv[2]);
    double fail_prob         = atof(argv[3]);
    string output_file       = argv[4];
    int    seed              = (argc > 5) ? atoi(argv[5]) : 42;
    int    repair_days       = (argc > 6) ? atoi(argv[6]) : 7;
    int    burst_interval    = (argc > 7) ? atoi(argv[7]) : 30;
    int    burst_size        = (argc > 8) ? atoi(argv[8]) : 3;
    int    max_fails_per_day = (argc > 9) ? atoi(argv[9]) : total_nodes;

    cout << "============================================" << endl;
    cout << "  GenTrace" << endl;
    cout << "============================================" << endl;
    printf("  Total nodes:       %d\n", total_nodes);
    printf("  Num days:          %d\n", num_days);
    printf("  Fail prob/day:     %.4f\n", fail_prob);
    printf("  Repair days:       %d\n", repair_days);
    printf("  Burst interval:    %s\n", burst_interval > 0
           ? to_string(burst_interval).c_str() : "disabled");
    if (burst_interval > 0)
        printf("  Burst size:        %d nodes\n", burst_size);
    printf("  Max fails/day:     %d\n", max_fails_per_day);
    printf("  Seed:              %d\n", seed);
    printf("  Output:            %s\n", output_file.c_str());
    cout << endl;

    mt19937 rng(seed);
    bernoulli_distribution fail_dist(fail_prob);

    ofstream outfile(output_file);
    if (!outfile.is_open()) {
        cerr << "Failed to open output file: " << output_file << endl;
        return 1;
    }

    outfile << "# Random trace generated by GenTrace" << endl;
    outfile << "# total_nodes=" << total_nodes
            << " num_days=" << num_days
            << " fail_prob=" << fail_prob
            << " repair_days=" << repair_days
            << " burst_interval=" << burst_interval
            << " burst_size=" << burst_size
            << " seed=" << seed << endl;
    outfile << "# Format: timestamp num_failures node_id1 node_id2 ..." << endl;
    outfile << "#" << endl;

    // recover_at[nid] = 恢复的天数
    unordered_map<int, int> recover_at;

    int total_fail_events = 0;
    int total_fail_nodes  = 0;
    int days_with_failure = 0;
    int burst_count       = 0;

    for (int day = 1; day <= num_days; day++) {

        // 先让到期的故障节点恢复
        for (auto it = recover_at.begin(); it != recover_at.end(); ) {
            if (it->second <= day)
                it = recover_at.erase(it);
            else
                ++it;
        }

        // 当前正常节点列表
        vector<int> healthy_nodes;
        for (int nid = 0; nid < total_nodes; nid++)
            if (!recover_at.count(nid))
                healthy_nodes.push_back(nid);

        unordered_set<int> today_fail_set;

        // --- 突发故障 ---
        if (burst_interval > 0 && day % burst_interval == 0 && !healthy_nodes.empty()) {
            // 从正常节点中随机选 burst_size 个集中故障
            shuffle(healthy_nodes.begin(), healthy_nodes.end(), rng);
            int actual_burst = min(burst_size, (int)healthy_nodes.size());
            for (int i = 0; i < actual_burst; i++)
                today_fail_set.insert(healthy_nodes[i]);
            burst_count++;
        }

        // --- 背景随机故障 ---
        for (int nid : healthy_nodes) {
            if (today_fail_set.count(nid)) continue; // 已被突发覆盖
            if (fail_dist(rng))
                today_fail_set.insert(nid);
        }

        // 转为有序列表
        vector<int> today_fails(today_fail_set.begin(), today_fail_set.end());
        sort(today_fails.begin(), today_fails.end());

        // 限制每天最大故障数
        if ((int)today_fails.size() > max_fails_per_day) {
            shuffle(today_fails.begin(), today_fails.end(), rng);
            today_fails.resize(max_fails_per_day);
            sort(today_fails.begin(), today_fails.end());
        }

        // 登记故障节点的恢复时间
        for (int nid : today_fails)
            recover_at[nid] = day + repair_days;

        // 只写有故障的天
        if (!today_fails.empty()) {
            outfile << day << " " << today_fails.size();
            for (int nid : today_fails)
                outfile << " " << nid;
            outfile << "\n";

            total_fail_events++;
            total_fail_nodes += (int)today_fails.size();
            days_with_failure++;
        }
    }

    outfile.close();

    cout << "============================================" << endl;
    cout << "  Summary" << endl;
    cout << "============================================" << endl;
    printf("  Days simulated:    %d\n", num_days);
    printf("  Days with failure: %d  (%.1f%%)\n",
           days_with_failure, 100.0 * days_with_failure / num_days);
    printf("  Burst events:      %d\n", burst_count);
    printf("  Total fail events: %d\n", total_fail_events);
    printf("  Total fail nodes:  %d\n", total_fail_nodes);
    printf("  Avg fails/event:   %.2f\n",
           days_with_failure > 0 ? 1.0 * total_fail_nodes / days_with_failure : 0.0);
    printf("  Output written to: %s\n", output_file.c_str());

    return 0;
}
